application: bloggart
version: master
api_version: 1
runtime: python27
threadsafe: false

#builtins:
#- datastore_admin: on

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /favicon.ico
  script: empty_favicon.py

- url: /_ah/queue/deferred
  script: deferred.py 
  login: admin

- url: /admin/.*
  script: admin.py
  login: admin

- url: /admin
  script: admin.py
  login: admin

- url: /.*\.(css|js)
  script: minifier.py

- url: /static/([^/]+)/(.*)
  static_files: themes/\1/static/\2
  upload: themes/[^/]+/static/.*

- url: /.*
  script: static.py

libraries:
- name: django
  version: "1.2"
